usr/share/ngqgis/doc/*
usr/share/ngqgis/i18n/*
usr/share/ngqgis/images/*
; usr/share/ngqgis/resources/qgis*.xml
; usr/share/ngqgis/resources/qgis*.xsd
usr/share/ngqgis/resources/*.txt
usr/share/ngqgis/resources/*.ini
usr/share/ngqgis/resources/data/*
usr/share/ngqgis/resources/metadata-ISO/*
usr/share/ngqgis/resources/opencl_programs/*
usr/share/ngqgis/resources/palettes/*
usr/share/ngqgis/resources/themes/*
usr/share/ngqgis/resources/spatialite.db
